# Poker League Configuration
# Shorter rounds for league play

rounds:
  - number: 1
    name: "10 / 20"
    duration: 15  # minutes
    is_break: false
  
  - number: 2
    name: "20 / 40"
    duration: 15  # minutes
    is_break: false
  
  - number: 3
    name: "Break"
    duration: 5  # minutes
    is_break: true
  
  - number: 4
    name: "30 / 60"
    duration: 15  # minutes
    is_break: false
  
  - number: 5
    name: "50 / 100"
    duration: 15  # minutes
    is_break: false
  
  - number: 6
    name: "Break"
    duration: 5  # minutes
    is_break: true
  
  - number: 7
    name: "75 / 150"
    duration: 15  # minutes
    is_break: false
  
  - number: 8
    name: "100 / 200"
    duration: 15  # minutes
    is_break: false

  - number: 9
    name: "Break"
    duration: 5  # minutes
    is_break: true
  
  - number: 10
    name: "150 / 300"
    duration: 15  # minutes
    is_break: false
  
  - number: 11
    name: "200 / 400"
    duration: 15  # minutes
    is_break: false

  - number: 12
    name: "Break"
    duration: 5  # minutes
    is_break: true
  
  - number: 13
    name: "300 / 600"
    duration: 15  # minutes
    is_break: false
  
  - number: 14
    name: "500 / 1000"
    duration: 180  # minutes
    is_break: false
