# Poker Tournament Configuration
# Define rounds with name, duration, and break indicators

rounds:
  - number: 1
    name: "25 / 50"
    duration: 20  # minutes
    is_break: false
  
  - number: 2
    name: "50 / 100"
    duration: 20  # minutes
    is_break: false
  
  - number: 3
    name: "Break"
    duration: 10  # minutes
    is_break: true
  
  - number: 4
    name: "75 / 150"
    duration: 20  # minutes
    is_break: false
  
  - number: 5
    name: "100 / 200"
    duration: 20  # minutes
    is_break: false
  
  - number: 6
    name: "Break"
    duration: 10  # minutes
    is_break: true
  
  - number: 7
    name: "200 / 400"
    duration: 20  # minutes
    is_break: false
  
  - number: 8
    name: "300 / 600"
    duration: 20  # minutes
    is_break: false

  - number: 9
    name: "Break"
    duration: 10  # minutes
    is_break: true
  
  - number: 10
    name: "400 / 800"
    duration: 20  # minutes
    is_break: false
  
  - number: 11
    name: "500 / 1000"
    duration: 20  # minutes
    is_break: false

  - number: 12
    name: "Break"
    duration: 10  # minutes
    is_break: true
  
  - number: 13
    name: "1000 / 2000"
    duration: 20  # minutes
    is_break: false
  
  - number: 14
    name: "2500 / 5000"
    duration: 360  # minutes
    is_break: false
    
